server:
  port: 8081
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user?useSSL=false
    username: root
    password: root4321
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis4321
  main:
    allow-bean-definition-overriding: true

#logging:
#  level:
#    root: debug
